directories:
  output: dist
  buildResources: build
appId: com.n-ziermann.antivirus
productName: Antivirus
executableName: Antivirus
files:
  - filter:
      - dist-electron
      - dist-react
icon: ./desktop-icon.png
extraResources:
  - from: signatures
    to: signatures
asarUnpack:
  - signatures/**
mac:
  target: dmg
linux:
  target: AppImage
  category: Utility
win:
  target:
    - portable
    - nsis
electronVersion: 37.2.5
